title: ICT Lab
description: Empowering Future Innovators in ICT
logo: "assets/ictlab.png"
remote_theme: Bilal2453/cayman-docs
plugins:
- jekyll-remote-theme

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects

# The cayman-docs theme does not support social_links or footer_text.
# social_links:
#   github: ICT-Lab
# footer_text: "Â© 2023 ICT Lab. All rights reserved."
